spring.application.name=e-commerce-app
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=${MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
#spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

Service.PRODUCTS_NOT_FOUND=No products found to display

logging.pattern.file=%d{yyyy-MM-dd HH:m:ss} {%thread} %-5level %logger{36} - %msg%n
logging.file.name=logs/Error.log

spring.config.import=classpath:account-validation.properties	