spring.application.name=e-commerce-demo
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=${MYSQL_DRIVER_URL}
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

Service.PRODUCTS_NOT_FOUND=No products found to display

logging.pattern.file=%d{yyyy-MM-dd HH:m:ss} {%thread} %-5level %logger{36} - %msg%n
logging.file.name=logs/Error.log

spring.config.import=classpath:account-validation.properties	